ALTER TABLE episodes ADD COLUMN IF NOT EXISTS width INT;
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS height INT;
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS fps DOUBLE PRECISION;
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS codec VARCHAR(100);
